export const FETCH_CARDS = "FETCH_CARDS"
export const CHANGE_TASK = "CHANGE_TASK"
export const CHANGE_CARD = "CHANGE_CARD"
export const DELETE_TASK = "DELETE_TASK"
export const DELETE_CARD = "DELETE_CARD"
export const POST_CARD = "POST_CARD"
export const POST_TASK = "POST_TASK"
