export const FETCH_CARDS = "FETCH_CARDS"
export const FETCH_TASK = "FETCH_TASK"
export const GET_TASKS = "GET TASKS"
export const CHANGE_TASK = "CHANGE_TASK"
export const CANCEL_PICKED_TASK = "CANCEL_PICKED_TASK"
export const CHANGE_CARD = "CHANGE_CARD"
export const DELETE_TASK = "DELETE_TASK"
export const DELETE_CARD = "DELETE_CARD"
export const POST_CARD = "POST_CARD"
export const POST_TASK = "POST_TASK"

export const USER_REGISTRATION = "USER_REGISTRATION"
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"
